# Generated by Django 5.0 on 2024-01-29 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_alter_member_options_member_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('Eid', models.AutoField(primary_key=True, serialize=False)),
                ('EAmount', models.IntegerField()),
                ('ENote', models.CharField(max_length=500)),
                ('EDate', models.DateField(max_length=350)),
                ('Category_name', models.CharField(max_length=250)),
                ('User_email', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('Iid', models.AutoField(primary_key=True, serialize=False)),
                ('IAmount', models.IntegerField()),
                ('INote', models.CharField(max_length=500)),
                ('IDate', models.DateField(max_length=350)),
                ('Category_name', models.CharField(max_length=250)),
                ('User_email', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
